# -*- coding: utf-8 -*-
"""HW3_Problem_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CESt8Wi0G45MvRqrec9j63wZOynmi3be
"""

# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import seaborn as sns
from google.colab import drive
# Connect to Google Drive
drive.mount('/content/drive')

# Read the diabetes.csv
file_path = '/content/drive/My Drive/Datasets/Diabetes.csv'
df = pd.DataFrame(pd.read_csv(file_path))

print('Number of examples m =', len(df))
df.head()

# Input variables (all 8 features) and output (Outcome: 1 = diabetes, 0 = no diabetes)
X = df.drop(columns='Outcome').values
y = df['Outcome'].values

#80/20 split into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size=0.2, random_state=100)

# Standardization: scaler is fitted on the training set only and then applied to the test set
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Add X_0 column of ones
X_train = np.hstack((np.ones((len(y_train), 1)), X_train))
X_test = np.hstack((np.ones((len(y_test), 1)), X_test))
print('Training examples:', len(y_train), '| Test examples:', len(y_test))

# Sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Cost function for logistic regression (binary cross entropy)
def compute_cost(X, y, theta):
    m = len(y)
    h = sigmoid(X.dot(theta))
    J = -1 / m * np.sum(y * np.log(h) + (1 - y) * np.log(1 - h))
    return J

# Accuracy with a threshold of 0.5
def compute_accuracy(X, y, theta):
    predictions = (sigmoid(X.dot(theta)) >= 0.5).astype(int)
    return np.mean(predictions == y)

# saves loss and accuracy for training and test set in every iteration
def gradient_descent(X, y, X_test, y_test, theta, alpha, iterations):
    m = len(y)
    history = {'train_loss': [], 'test_loss': [], 'train_acc': [], 'test_acc': []}

    for i in range(iterations):
        predictions = sigmoid(X.dot(theta))
        errors = np.subtract(predictions, y)
        sum_delta = (alpha / m) * X.transpose().dot(errors)
        theta = theta - sum_delta
        history['train_loss'].append(compute_cost(X, y, theta))
        history['test_loss'].append(compute_cost(X_test, y_test, theta))
        history['train_acc'].append(compute_accuracy(X, y, theta))
        history['test_acc'].append(compute_accuracy(X_test, y_test, theta))

    return theta, history

# Training loop over learning rates
iterations = 1000
alphas = [0.1, 0.05, 0.01]
results = {}

for alpha in alphas:
    theta0 = np.zeros(X_train.shape[1])
    theta, history = gradient_descent(X_train, y_train, X_test, y_test, theta0, alpha, iterations)
    results[alpha] = {'theta': theta, 'history': history}
    print(f"alpha={alpha:<5} | final train loss={history['train_loss'][-1]:.4f} | final test loss={history['test_loss'][-1]:.4f} "
          f"| train acc={history['train_acc'][-1]:.4f} | test acc={history['test_acc'][-1]:.4f}")

# Best learning rate = lowest final training loss
best_alpha = min(alphas, key=lambda a: results[a]['history']['train_loss'][-1])
theta = results[best_alpha]['theta']
history = results[best_alpha]['history']
print('\nBest alpha:', best_alpha)
feature_names = ['theta_0 (bias)'] + list(df.drop(columns='Outcome').columns)
for name, t in zip(feature_names, theta):
    print(f"{name:>26s} = {t: .4f}")

# Plot loss and accuracy over the iterations
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
axes[0].plot(range(1, iterations + 1), history['train_loss'], label='Training loss')
axes[0].plot(range(1, iterations + 1), history['test_loss'], label='Test loss')
axes[0].set_xlabel('Iteration')
axes[0].set_ylabel('Cost J(theta)')
axes[0].set_title(f'Loss over iterations (alpha={best_alpha})')
axes[0].grid(True)
axes[0].legend()

axes[1].plot(range(1, iterations + 1), history['train_acc'], label='Training accuracy')
axes[1].plot(range(1, iterations + 1), history['test_acc'], label='Test accuracy')
axes[1].set_xlabel('Iteration')
axes[1].set_ylabel('Accuracy')
axes[1].set_title(f'Accuracy over iterations (alpha={best_alpha})')
axes[1].grid(True)
axes[1].legend()
plt.tight_layout()
plt.savefig('problem_1_training.png', dpi=110)
plt.show()

# Accuracy, precision, recall and F1 score
def scores(y_true, y_pred):
    (TN, FP), (FN, TP) = confusion_matrix(y_true, y_pred)
    accuracy = (TP + TN) / (TP + TN + FP + FN)
    precision = TP / (TP + FP)
    recall = TP / (TP + FN)
    f1 = 2 * precision * recall / (precision + recall)
    return accuracy, precision, recall, f1

# Confusion matrix
# Layout like sklearn: rows = actual label, columns = predicted label
def confusion_matrix(y_true, y_pred):
    TN = np.sum((y_true == 0) & (y_pred == 0))
    FP = np.sum((y_true == 0) & (y_pred == 1))
    FN = np.sum((y_true == 1) & (y_pred == 0))
    TP = np.sum((y_true == 1) & (y_pred == 1))
    return np.array([[TN, FP], [FN, TP]])

# Evaluation
y_pred = (sigmoid(X_test.dot(theta)) >= 0.5).astype(int)
accuracy, precision, recall, f1 = scores(y_test, y_pred)
print('Accuracy: ', round(accuracy, 4))
print('Precision:', round(precision, 4))
print('Recall:   ', round(recall, 4))
print('F1 score: ', round(f1, 4))

# Confusion matrix
cnf_matrix = confusion_matrix(y_test, y_pred)
print(cnf_matrix)

plt.figure(figsize=(6, 5))
sns.heatmap(pd.DataFrame(cnf_matrix), annot=True, cmap='YlGnBu', fmt='g',
            xticklabels=['No diabetes (0)', 'Diabetes (1)'], yticklabels=['No diabetes (0)', 'Diabetes (1)'])
plt.title('Problem 1: Confusion matrix')
plt.ylabel('Actual label')
plt.xlabel('Predicted label')
plt.tight_layout()
plt.savefig('problem_1_confusion_matrix.png', dpi=110)
plt.show()