# -*- coding: utf-8 -*-
"""HW3_Problem_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gTfDbOHizD7K9F7yom6KOHECpghey9yx
"""

# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
import seaborn as sns
from google.colab import drive
# Connect to Google Drive
drive.mount('/content/drive')

# Read the Cancer.csv
file_path = '/content/drive/My Drive/Datasets/Cancer.csv'
df = pd.DataFrame(pd.read_csv(file_path))

print('Number of examples m =', len(df))
df.head()

# Remove the id column and the empty column at the end
df = df.drop(columns=['id', 'Unnamed: 32'])
df.head()

# Input variables (all 30 features)
X = df.drop(columns='diagnosis').values
# Output: malignant (M) = 1 (positive class), benign (B) = 0
y = df['diagnosis'].map({'M': 1, 'B': 0}).values
print('Malignant:', np.sum(y == 1), '| Benign:', np.sum(y == 0))

# 80/20 split into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size=0.2, random_state=100)

# Standardization: scaler is fitted on the training set only and then applied to the test set
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Add X_0 column of ones
X_train = np.hstack((np.ones((len(y_train), 1)), X_train))
X_test = np.hstack((np.ones((len(y_test), 1)), X_test))
print('Training examples:', len(y_train), '| Test examples:', len(y_test))

# Sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Cost function for logistic regression (binary cross entropy)
# lambda_ > 0 adds the weight penalty (L2), theta_0 (bias) is not penalized
def compute_cost(X, y, theta, lambda_=0):
    m = len(y)
    h = np.clip(sigmoid(X.dot(theta)), 1e-15, 1 - 1e-15)   # clip to avoid log(0)
    J = -1 / m * np.sum(y * np.log(h) + (1 - y) * np.log(1 - h))
    J += lambda_ / (2 * m) * np.sum(np.square(theta[1:]))
    return J

# Accuracy with a threshold of 0.5
def compute_accuracy(X, y, theta):
    predictions = (sigmoid(X.dot(theta)) >= 0.5).astype(int)
    return np.mean(predictions == y)

# Gradient descent for logistic regression with optional weight penalty
# the training loss includes the penalty, the test loss is calculated without penalty
def gradient_descent(X, y, X_test, y_test, theta, alpha, iterations, lambda_=0):
    m = len(y)
    history = {'train_loss': [], 'test_loss': [], 'train_acc': [], 'test_acc': []}

    for i in range(iterations):
        predictions = sigmoid(X.dot(theta))
        errors = np.subtract(predictions, y)
        gradient = (1 / m) * X.transpose().dot(errors)
        gradient[1:] += (lambda_ / m) * theta[1:]        # penalty term (only for lambda_ > 0)
        theta = theta - alpha * gradient
        history['train_loss'].append(compute_cost(X, y, theta, lambda_))
        history['test_loss'].append(compute_cost(X_test, y_test, theta))
        history['train_acc'].append(compute_accuracy(X, y, theta))
        history['test_acc'].append(compute_accuracy(X_test, y_test, theta))

    return theta, history

# Evaluation on the test set
def evaluate(theta):
    y_pred = (sigmoid(X_test.dot(theta)) >= 0.5).astype(int)
    scores = {'Accuracy': metrics.accuracy_score(y_test, y_pred),
              'Precision': metrics.precision_score(y_test, y_pred),
              'Recall': metrics.recall_score(y_test, y_pred),
              'F1 score': metrics.f1_score(y_test, y_pred)}
    return y_pred, scores

def plot_training(history, iterations, title, filename):
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))
    axes[0].plot(range(1, iterations + 1), history['train_loss'], label='Training loss')
    axes[0].plot(range(1, iterations + 1), history['test_loss'], label='Test loss')
    axes[0].set_xlabel('Iteration')
    axes[0].set_ylabel('Cost J(theta)')
    axes[0].set_yscale('log')
    axes[0].set_title(f'{title}: Loss')
    axes[0].grid(True)
    axes[0].legend()

    axes[1].plot(range(1, iterations + 1), history['train_acc'], label='Training accuracy')
    axes[1].plot(range(1, iterations + 1), history['test_acc'], label='Test accuracy')
    axes[1].set_xlabel('Iteration')
    axes[1].set_ylabel('Accuracy')
    axes[1].set_ylim(0.9, 1.0)
    axes[1].set_title(f'{title}: Accuracy')
    axes[1].grid(True)
    axes[1].legend()
    plt.tight_layout()
    plt.savefig(filename, dpi=110)
    plt.show()

def plot_confusion_matrix(y_pred, title, filename):
    cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
    print(cnf_matrix)
    plt.figure(figsize=(6, 5))
    sns.heatmap(pd.DataFrame(cnf_matrix), annot=True, cmap='YlGnBu', fmt='g',
                xticklabels=['Benign (0)', 'Malignant (1)'], yticklabels=['Benign (0)', 'Malignant (1)'])
    plt.title(title)
    plt.ylabel('Actual label')
    plt.xlabel('Predicted label')
    plt.tight_layout()
    plt.savefig(filename, dpi=110)
    plt.show()

# Problem 2.1: Logistic regression with all 30 features, no penalty
iterations = 5000
alphas = [0.1, 0.05, 0.01]
results = {}

for alpha in alphas:
    theta0 = np.zeros(X_train.shape[1])
    theta, history = gradient_descent(X_train, y_train, X_test, y_test, theta0, alpha, iterations)
    results[alpha] = {'theta': theta, 'history': history}
    print(f"alpha={alpha:<5} | final train loss={history['train_loss'][-1]:.4f} | final test loss={history['test_loss'][-1]:.4f} "
          f"| train acc={history['train_acc'][-1]:.4f} | test acc={history['test_acc'][-1]:.4f}")

# Best learning rate = lowest final training loss
best_alpha = min(alphas, key=lambda a: results[a]['history']['train_loss'][-1])
theta_1 = results[best_alpha]['theta']
print('\nBest alpha:', best_alpha)

plot_training(results[best_alpha]['history'], iterations,
              f'Problem 2.1 (alpha={best_alpha})', 'problem_2_1_training.png')

y_pred_1, scores_1 = evaluate(theta_1)
for name, s in scores_1.items():
    print(f'{name:<10} {s:.4f}')
plot_confusion_matrix(y_pred_1, 'Problem 2.1: Confusion matrix', 'problem_2_1_confusion_matrix.png')

# Problem 2.2: Logistic regression with weight penalty (L2)
lambdas = [0, 1, 5, 10]
results_pen = {}

for lam in lambdas:
    theta0 = np.zeros(X_train.shape[1])
    theta, history = gradient_descent(X_train, y_train, X_test, y_test, theta0, best_alpha, iterations, lam)
    _, scores = evaluate(theta)
    results_pen[lam] = {'theta': theta, 'history': history, 'scores': scores}
    print(f"lambda={lam:<3} | train loss={history['train_loss'][-1]:.4f} | test loss={history['test_loss'][-1]:.4f} "
          f"| test acc={scores['Accuracy']:.4f} | precision={scores['Precision']:.4f} | recall={scores['Recall']:.4f} "
          f"| F1={scores['F1 score']:.4f}")

# Best lambda = highest F1 score on the test set
best_lambda = max([l for l in lambdas if l > 0], key=lambda l: results_pen[l]['scores']['F1 score'])
theta_2 = results_pen[best_lambda]['theta']
print('\nBest lambda:', best_lambda)

plot_training(results_pen[best_lambda]['history'], iterations,
              f'Problem 2.2 (alpha={best_alpha}, lambda={best_lambda})', 'problem_2_2_training.png')

y_pred_2, scores_2 = evaluate(theta_2)
for name, s in scores_2.items():
    print(f'{name:<10} {s:.4f}')
plot_confusion_matrix(y_pred_2, f'Problem 2.2: Confusion matrix (lambda={best_lambda})', 'problem_2_2_confusion_matrix.png')

# Comparison of the test accuracy over the iterations with and without penalty
plt.figure(figsize=(10, 6))
plt.plot(range(1, iterations + 1), results_pen[0]['history']['test_acc'], label='Without penalty')
plt.plot(range(1, iterations + 1), results_pen[best_lambda]['history']['test_acc'], label=f'With penalty (lambda={best_lambda})')
plt.xlabel('Iteration')
plt.ylabel('Test accuracy')
plt.ylim(0.9, 1.0)
plt.title('Problem 2: Test accuracy with and without weight penalty')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.savefig('problem_2_comparison.png', dpi=110)
plt.show()