# -*- coding: utf-8 -*-
"""Multiple_Linear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_duVP1yfqvftwlQQCXB5p7xag5g9xMfl
"""

# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display
from google.colab import drive
# Connect to Google Drive
drive.mount('/content/drive')

# Read the D3.csv
file_path = '/content/drive/My Drive/Datasets/D3.csv'
df = pd.DataFrame(pd.read_csv(file_path))

# Extract the values
m = len(df)  # number of training examples
y = df.values[:,3]
print('Number of training examples m =', m)
df.head()

# Reshape the data matrix
X_0 = np.ones((m, 1))
X_1 = df['X1'].values.reshape(m, 1)
X_2 = df['X2'].values.reshape(m, 1)
X_3 = df['X3'].values.reshape(m, 1)

X = np.hstack((X_0, X_1, X_2, X_3))

# Cost function (https://github.com/HamedTabkhi/Intro-to-ML/blob/main/IntroCodes/LinearRegression.ipynb)
def compute_cost(X, y, theta):
    """
    Compute cost for linear regression.

    Parameters:
    X : 2D array where each row represents the training example and each column represent the feature
        m = number of training examples
        n = number of features (including X_0 column of ones)
    y : 1D array of labels/target values for each training example. dimension(m)
    theta : 1D array of fitting parameters or weights. Dimension (n)

    Returns:
    J : Scalar value, the cost
    """
    predictions = X.dot(theta)
    errors = np.subtract(predictions, y)
    sqrErrors = np.square(errors)
    J = 1 / (2 * m) * np.sum(sqrErrors)
    return J

# Gradient descent function (https://github.com/HamedTabkhi/Intro-to-ML/blob/main/IntroCodes/LinearRegression.ipynb)
def gradient_descent(X, y, theta, alpha, iterations):
    """
    Compute the optimal parameters using gradient descent for linear regression.

    Parameters:
    X : 2D array where each row represents the training example and each column represents the feature
        m = number of training examples
        n = number of features (including X_0 column of ones)
    y : 1D array of labels/target values for each training example. dimension(m)
    theta : 1D array of fitting parameters or weights. Dimension (n)
    alpha : Learning rate (scalar)
    iterations : Number of iterations (scalar)

    Returns:
    theta : Updated values of fitting parameters or weights after 'iterations' iterations. Dimension (n)
    cost_history : Array containing the cost for each iteration. Dimension (iterations)
    """

    m = len(y)  # Number of training examples
    cost_history = np.zeros(iterations)

    for i in range(iterations):
        predictions = X.dot(theta)
        errors = np.subtract(predictions, y)
        sum_delta = (alpha / m) * X.transpose().dot(errors)
        theta -= sum_delta
        cost_history[i] = compute_cost(X, y, theta)

    return theta, cost_history

# Training
iterations = 1000
alphas = [0.1, 0.05, 0.01]

results = {}

for alpha in alphas:
    theta = np.zeros(4)

    theta, cost_history = gradient_descent(
        X, y, theta, alpha, iterations
    )

    results[alpha] = {
        'theta': theta,
        'cost_history': cost_history
    }

    print(
        f"alpha={alpha} | "
        f"theta={theta} | "
        f"final cost={cost_history[-1]:.4f}"
    )

# Plotting
plt.figure(figsize=(10, 6))

for alpha in alphas:
    cost_history = results[alpha]['cost_history']
    plt.plot(
        range(1, iterations + 1),
        cost_history,
        label=f'alpha={alpha}'
    )

plt.xlabel('Iteration')
plt.ylabel('Cost J(theta)')
plt.title('Problem 2: Cost vs. Iteration')
plt.grid(True)
plt.legend()
plt.tight_layout()

plt.savefig('problem2_cost.png', dpi=110)
plt.show()

# Prediction
theta = results[0.1]['theta']
print(theta)
x_pred = np.array([
    [1, 1, 1],
    [2, 0, 4],
    [3, 2, 1]
])

X_pred = np.column_stack((np.ones(3), x_pred))

y_pred = X_pred.dot(theta)

print("(1,1,1) ->", y_pred[0])
print("(2,0,4) ->", y_pred[1])
print("(3,2,1) ->", y_pred[2])