# -*- coding: utf-8 -*-
"""HW4_Problem_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vF4_HwgvecIDhqks4pE5DVdyL3-GA0Ln
"""

# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn import metrics
from google.colab import drive

# Connect to Google Drive
drive.mount('/content/drive')

# Read the Cancer.csv
file_path = '/content/drive/My Drive/Datasets/Cancer.csv'
df = pd.DataFrame(pd.read_csv(file_path))

# Remove the id column and the empty column at the end
df = df.drop(columns=['id', 'Unnamed: 32'])
print('Number of examples m =', len(df))
df.head()

# Input variables (all 30 features)
X = df.drop(columns='diagnosis').values
# Output: malignant (M) = 1 (positive class), benign (B) = 0
y = df['diagnosis'].map({'M': 1, 'B': 0}).values
print('Malignant:', np.sum(y == 1), '| Benign:', np.sum(y == 0))

# 80/20 split into training and test set (same split as in Homework 3)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size=0.2, random_state=100)

# Standardization: scaler is fitted on the training set only and then applied to the test set
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print('Training examples:', len(y_train), '| Test examples:', len(y_test))

# SVM classifier with different kernels
# For every kernel the penalty parameter C is chosen with 5-fold cross-validation on the training set
kernels = ['linear', 'poly', 'rbf', 'sigmoid']
Cs = [0.01, 0.1, 1, 10, 100]
results = {}

for kernel in kernels:
    grid = GridSearchCV(SVC(kernel=kernel), {'C': Cs}, cv=5)
    grid.fit(X_train, y_train)
    model = grid.best_estimator_
    y_pred = model.predict(X_test)
    results[kernel] = {'C': grid.best_params_['C'],
                       'cv_scores': grid.cv_results_['mean_test_score'],
                       'y_pred': y_pred,
                       'Train accuracy': model.score(X_train, y_train),
                       'Accuracy': metrics.accuracy_score(y_test, y_pred),
                       'Precision': metrics.precision_score(y_test, y_pred),
                       'Recall': metrics.recall_score(y_test, y_pred),
                       'F1 score': metrics.f1_score(y_test, y_pred),
                       'Support vectors': model.n_support_.sum()}
    print(f"{kernel:<8} | C={results[kernel]['C']:<5} | train acc={results[kernel]['Train accuracy']:.4f} "
          f"| test acc={results[kernel]['Accuracy']:.4f} | precision={results[kernel]['Precision']:.4f} "
          f"| recall={results[kernel]['Recall']:.4f} | F1={results[kernel]['F1 score']:.4f} "
          f"| support vectors={results[kernel]['Support vectors']}")

# Results of the logistic regression from Homework 3 (Problem 2.1, same split)
hw3 = {'Accuracy': 0.9737, 'Precision': 1.0, 'Recall': 0.9388, 'F1 score': 0.9684}

# Plot accuracy, precision, recall and F1 score for every kernel and the logistic regression
score_names = ['Accuracy', 'Precision', 'Recall', 'F1 score']
models = kernels + ['Logistic regression (HW3)']
values = [[results[k][s] for s in score_names] for k in kernels] + [[hw3[s] for s in score_names]]

x = np.arange(len(score_names))
width = 0.16
plt.figure(figsize=(12, 6))
for i, (name, vals) in enumerate(zip(models, values)):
    bars = plt.bar(x + (i - 2) * width, vals, width, label=name)
    plt.bar_label(bars, fmt='%.3f', fontsize=7, rotation=90, padding=2)
plt.xticks(x, score_names)
plt.ylim(0.75, 1.05)
plt.ylabel('Score on the test set')
plt.title('Problem 1: SVM kernels vs. logistic regression')
plt.grid(True, axis='y')
plt.legend(loc='upper center', bbox_to_anchor=(0.5, -0.08), ncol=5)
plt.tight_layout()
plt.savefig('problem_1_scores.png', dpi=110)
plt.show()

# Plot the cross-validation accuracy over C for every kernel
plt.figure(figsize=(10, 6))
for kernel in kernels:
    plt.plot(Cs, results[kernel]['cv_scores'], marker='o', label=kernel)
plt.xscale('log')
plt.xlabel('C')
plt.ylabel('Cross-validation accuracy')
plt.title('Problem 1: Accuracy for different C and kernels')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.savefig('problem_1_C.png', dpi=110)
plt.show()

# Confusion matrix for every kernel
fig, axes = plt.subplots(2, 2, figsize=(11, 9))
for ax, kernel in zip(axes.ravel(), kernels):
    cnf_matrix = metrics.confusion_matrix(y_test, results[kernel]['y_pred'])
    sns.heatmap(pd.DataFrame(cnf_matrix), annot=True, cmap='YlGnBu', fmt='g', ax=ax,
                xticklabels=['Benign (0)', 'Malignant (1)'], yticklabels=['Benign (0)', 'Malignant (1)'])
    ax.set_title(f"{kernel} kernel (C={results[kernel]['C']})")
    ax.set_ylabel('Actual label')
    ax.set_xlabel('Predicted label')
plt.tight_layout()
plt.savefig('problem_1_confusion_matrices.png', dpi=110)
plt.show()