# -*- coding: utf-8 -*-
"""HW4_Problem_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17LHt6yrMn6txEkxky89aVyNY7JpLD3zP
"""

# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.linear_model import Ridge
from sklearn import metrics
from google.colab import drive

# Connect to Google Drive
drive.mount('/content/drive')

# Read the Housing.csv
file_path = '/content/drive/My Drive/Datasets/Housing.csv'
df = pd.DataFrame(pd.read_csv(file_path))

# Map yes/no variables to 1/0
binary_vars = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']
df[binary_vars] = df[binary_vars].apply(lambda x: x.map({'yes': 1, 'no': 0}))
print('Number of examples m =', len(df))
df.head()

# Input variables
variables = ['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'parking', 'prefarea']

# 80/20 split into training and test set (same split as in Homework 2)
df_train, df_test = train_test_split(df, train_size=0.8, test_size=0.2, random_state=100)
X_train = df_train[variables].values.astype(float)
X_test = df_test[variables].values.astype(float)
y_train = df_train['price'].values
y_test = df_test['price'].values
print('Training examples:', len(y_train), '| Test examples:', len(y_test))

# Standardization of the inputs: fitted on the training set only
scaler_X = StandardScaler()
X_train = scaler_X.fit_transform(X_train)
X_test = scaler_X.transform(X_test)

# SVR is very sensitive to the scale of the output (epsilon = 0.1, C = 1 by default),
# so the price is standardized for the training and transformed back for the evaluation
scaler_y = StandardScaler()
y_train_s = scaler_y.fit_transform(y_train.reshape(-1, 1)).ravel()

def to_price(y_s):
    return scaler_y.inverse_transform(y_s.reshape(-1, 1)).ravel()

# Cost function
def compute_cost(y, y_pred):
    return 1 / (2 * len(y)) * np.sum(np.square(y_pred - y))

def evaluate(y, y_pred):
    return {'R2': metrics.r2_score(y, y_pred),
            'Cost': compute_cost(y, y_pred),
            'RMSE': np.sqrt(metrics.mean_squared_error(y, y_pred)),
            'MAE': metrics.mean_absolute_error(y, y_pred)}

# SVR with different kernels
# For every kernel the penalty parameter C is chosen with 5-fold cross-validation on the training set
kernels = ['linear', 'poly', 'rbf', 'sigmoid']
Cs = [0.01, 0.1, 1, 10, 100]
results = {}

for kernel in kernels:
    grid = GridSearchCV(SVR(kernel=kernel), {'C': Cs}, cv=5, scoring='r2')
    grid.fit(X_train, y_train_s)
    model = grid.best_estimator_
    y_pred = to_price(model.predict(X_test))
    results[kernel] = {'model': model, 'C': grid.best_params_['C'],
                       'cv_scores': grid.cv_results_['mean_test_score'], 'y_pred': y_pred,
                       'Train R2': metrics.r2_score(y_train, to_price(model.predict(X_train))),
                       **evaluate(y_test, y_pred)}
    print(f"{kernel:<8} | C={results[kernel]['C']:<5} | train R2={results[kernel]['Train R2']:.4f} "
          f"| test R2={results[kernel]['R2']:.4f} | cost={results[kernel]['Cost']:.4e} "
          f"| RMSE={results[kernel]['RMSE']:.0f} | MAE={results[kernel]['MAE']:.0f}")

# Linear regression with L2 penalty from Homework 2 (Problem 3b, standardization, lambda = 50)
# Ridge minimizes the same cost function as the gradient descent with penalty from Homework 2
ridge = Ridge(alpha=50).fit(X_train, y_train)
y_pred_ridge = ridge.predict(X_test)
results_ridge = {'Train R2': metrics.r2_score(y_train, ridge.predict(X_train)), **evaluate(y_test, y_pred_ridge)}
print(f"Ridge (HW2) | train R2={results_ridge['Train R2']:.4f} | test R2={results_ridge['R2']:.4f} "
      f"| cost={results_ridge['Cost']:.4e} | RMSE={results_ridge['RMSE']:.0f} | MAE={results_ridge['MAE']:.0f}")

# Plot the regression models similar to the SVR sample code:
# price over area, all other inputs are kept at their average value
colors = {'linear': 'c', 'poly': 'cornflowerblue', 'rbf': 'navy', 'sigmoid': 'green'}
area_raw = np.linspace(df_train['area'].min(), df_train['area'].max(), 300)
X_line = np.tile(scaler_X.mean_, (len(area_raw), 1))
X_line[:, 0] = area_raw
X_line = scaler_X.transform(X_line)

lw = 2
plt.figure(figsize=(10, 6))
plt.scatter(df_test['area'], y_test, color='darkorange', label='test data')
for kernel in kernels:
    plt.plot(area_raw, to_price(results[kernel]['model'].predict(X_line)), color=colors[kernel], lw=lw,
             label=f'{kernel} model')
plt.plot(area_raw, ridge.predict(X_line), color='red', lw=lw, linestyle='--', label='Linear regression (HW2)')
plt.xlabel('area')
plt.ylabel('price')
plt.title('Support Vector Regression (other inputs at their average)')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig('problem_2_svr_area.png', dpi=110)
plt.show()

# Predicted vs. actual price on the test set for every kernel
fig, axes = plt.subplots(2, 2, figsize=(11, 10))
lims = [y_test.min() * 0.9, y_test.max() * 1.05]
for ax, kernel in zip(axes.ravel(), kernels):
    ax.scatter(y_test, results[kernel]['y_pred'], color='darkorange', s=20)
    ax.plot(lims, lims, color='black', lw=1, label='perfect prediction')
    ax.set_xlim(lims)
    ax.set_ylim(lims)
    ax.set_title(f"{kernel} kernel (C={results[kernel]['C']}, R2={results[kernel]['R2']:.3f})")
    ax.set_xlabel('Actual price')
    ax.set_ylabel('Predicted price')
    ax.grid(True)
    ax.legend()
plt.tight_layout()
plt.savefig('problem_2_pred_vs_actual.png', dpi=110)
plt.show()

# Compare the R2 score (accuracy) of all models
names = kernels + ['Linear regression (HW2)']
train_r2 = [results[k]['Train R2'] for k in kernels] + [results_ridge['Train R2']]
test_r2 = [results[k]['R2'] for k in kernels] + [results_ridge['R2']]
x = np.arange(len(names))
plt.figure(figsize=(10, 6))
bars1 = plt.bar(x - 0.2, train_r2, 0.4, label='Training R2')
bars2 = plt.bar(x + 0.2, test_r2, 0.4, label='Test R2')
plt.bar_label(bars1, fmt='%.3f', fontsize=8)
plt.bar_label(bars2, fmt='%.3f', fontsize=8)
plt.xticks(x, names)
plt.ylim(0, 1)
plt.ylabel('R2 score')
plt.title('Problem 2: R2 score of the SVR kernels and the linear regression')
plt.grid(True, axis='y')
plt.legend()
plt.tight_layout()
plt.savefig('problem_2_r2.png', dpi=110)
plt.show()

# Cross-validation R2 over C for every kernel
plt.figure(figsize=(10, 6))
for kernel in kernels:
    plt.plot(Cs, results[kernel]['cv_scores'], marker='o', color=colors[kernel], label=kernel)
plt.xscale('log')
plt.ylim(-1, 1)
plt.xlabel('C')
plt.ylabel('Cross-validation R2')
plt.title('Problem 2: R2 for different C and kernels')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.savefig('problem_2_C.png', dpi=110)
plt.show()