# -*- coding: utf-8 -*-
"""HW2_Problem_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PGm9r53dVW7PPbG5fk8weRzNwKZzdlfT
"""

# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from google.colab import drive
# Connect to Google Drive
drive.mount('/content/drive')

# Read the Housing.csv
file_path = '/content/drive/My Drive/Datasets/Housing.csv'
df = pd.DataFrame(pd.read_csv(file_path))

# Map yes/no variables to 1/0 (needed for part b)
binary_vars = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']
df[binary_vars] = df[binary_vars].apply(lambda x: x.map({'yes': 1, 'no': 0}))

print('Number of examples m =', len(df))
df.head()

# Input variables for part a and b
variables_a = ['area', 'bedrooms', 'bathrooms', 'stories', 'parking']
variables_b = ['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad', 'guestroom', 'basement',
               'hotwaterheating', 'airconditioning', 'parking', 'prefarea']

# 80/20 split into training and validation set (same split for a and b)
df_train, df_val = train_test_split(df, train_size=0.8, test_size=0.2, random_state=100)
y_train = df_train['price'].values
y_val = df_val['price'].values
m_train, m_val = len(y_train), len(y_val)
print('Training examples:', m_train, '| Validation examples:', m_val)

# Build data matrices (add X_0 column of ones) with input scaling
# The scaler is fitted on the training set only and then applied to the validation set
# The output (price) is not scaled
def build_X(variables, scaler):
    X_tr = scaler.fit_transform(df_train[variables].values.astype(float))
    X_va = scaler.transform(df_val[variables].values.astype(float))
    X_train = np.hstack((np.ones((m_train, 1)), X_tr))
    X_val = np.hstack((np.ones((m_val, 1)), X_va))
    return X_train, X_val

# Cost function (https://github.com/HamedTabkhi/Intro-to-ML/blob/main/IntroCodes/LinearRegression.ipynb)
def compute_cost(X, y, theta):
    """
    Compute cost for linear regression.

    Parameters:
    X : 2D array (m x n), including X_0 column of ones
    y : 1D array of target values. Dimension (m)
    theta : 1D array of fitting parameters. Dimension (n)

    Returns:
    J : Scalar value, the cost
    """
    m = len(y)
    predictions = X.dot(theta)
    errors = np.subtract(predictions, y)
    sqrErrors = np.square(errors)
    J = 1 / (2 * m) * np.sum(sqrErrors)
    return J

# Gradient descent function (https://github.com/HamedTabkhi/Intro-to-ML/blob/main/IntroCodes/LinearRegression.ipynb)
# extended by the validation loss per iteration
def gradient_descent(X, y, X_val, y_val, theta, alpha, iterations):
    m = len(y)
    train_history = np.full(iterations, np.nan)
    val_history = np.full(iterations, np.nan)

    for i in range(iterations):
        with np.errstate(over='ignore', invalid='ignore'):
            predictions = X.dot(theta)
            errors = np.subtract(predictions, y)
            sum_delta = (alpha / m) * X.transpose().dot(errors)
            theta = theta - sum_delta
            cost = compute_cost(X, y, theta)
        if not np.isfinite(cost):
            break
        train_history[i] = cost
        val_history[i] = compute_cost(X_val, y_val, theta)

    return theta, train_history, val_history

# Convergence check
def converged_at(history, delta=1e-6):
    rel_change = np.abs(np.diff(history)) / history[1:]
    idx = np.where(rel_change < delta)[0]
    return int(idx[0]) + 2 if len(idx) > 0 else None

# Training loop over learning rates
def train(variables, alphas, iterations, scaler):
    X_train, X_val = build_X(variables, scaler)
    results = {}

    for alpha in alphas:
        theta0 = np.zeros(X_train.shape[1])
        theta, train_history, val_history = gradient_descent(
            X_train, y_train, X_val, y_val, theta0, alpha, iterations
        )
        results[alpha] = {'theta': theta, 'train': train_history, 'val': val_history}

        if np.isnan(train_history[-1]):
            print(f"alpha={alpha:<6} | diverged after {np.count_nonzero(~np.isnan(train_history))} iterations")
        else:
            it = converged_at(train_history)
            print(f"alpha={alpha:<6} | final train cost={train_history[-1]:.4e} | final val cost={val_history[-1]:.4e} "
                  f"| converged at iteration {it if it else '> ' + str(iterations)}")

    # Best learning rate = lowest final training cost (diverged runs excluded)
    best_alpha = min([a for a in alphas if np.isfinite(results[a]['train'][-1])],
                     key=lambda a: results[a]['train'][-1])
    print('\nBest alpha:', best_alpha)
    for name, t in zip(['theta_0 (bias)'] + variables, results[best_alpha]['theta']):
        print(f"{name:>16s} = {t: .4f}")
    return results, best_alpha

# Plot training and validation loss for normalization and standardization in one graph
def plot_scaling(res_norm, alpha_norm, res_std, alpha_std, iterations, title, filename):
    plt.figure(figsize=(10, 6))
    plt.plot(range(1, iterations + 1), res_norm[alpha_norm]['train'], color='tab:blue', label=f'Normalization - Training (alpha={alpha_norm})')
    plt.plot(range(1, iterations + 1), res_norm[alpha_norm]['val'], color='tab:blue', linestyle='--', label=f'Normalization - Validation (alpha={alpha_norm})')
    plt.plot(range(1, iterations + 1), res_std[alpha_std]['train'], color='tab:orange', label=f'Standardization - Training (alpha={alpha_std})')
    plt.plot(range(1, iterations + 1), res_std[alpha_std]['val'], color='tab:orange', linestyle='--', label=f'Standardization - Validation (alpha={alpha_std})')
    plt.xlabel('Iteration')
    plt.ylabel('Cost J(theta)')
    plt.yscale('log')
    plt.title(title)
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig(filename, dpi=110)
    plt.show()

# Training settings (the scaled inputs now work with the given learning rates)
iterations = 2000
alphas = [0.1, 0.05, 0.01]

# Training for a)
print('--- a) Normalization ---')
results_a_norm, best_alpha_a_norm = train(variables_a, alphas, iterations, MinMaxScaler())
print('\n--- a) Standardization ---')
results_a_std, best_alpha_a_std = train(variables_a, alphas, iterations, StandardScaler())

# Plotting for a)
plot_scaling(results_a_norm, best_alpha_a_norm, results_a_std, best_alpha_a_std, iterations,
             'Problem 2a: Normalization vs. Standardization', 'problem_2a_loss.png')

# Training for b)
print('\n--- b) Normalization ---')
results_b_norm, best_alpha_b_norm = train(variables_b, alphas, iterations, MinMaxScaler())
print('\n--- b) Standardization ---')
results_b_std, best_alpha_b_std = train(variables_b, alphas, iterations, StandardScaler())

# Plotting for b)
plot_scaling(results_b_norm, best_alpha_b_norm, results_b_std, best_alpha_b_std, iterations,
             'Problem 2b: Normalization vs. Standardization', 'problem_2b_loss.png')

# Comparison normalization vs. standardization
print(f"\n{'Model':<22} | {'alpha':>5} | {'train cost':>11} | {'val cost':>11}")
for label, res, a in [('2a normalization', results_a_norm, best_alpha_a_norm),
                      ('2a standardization', results_a_std, best_alpha_a_std),
                      ('2b normalization', results_b_norm, best_alpha_b_norm),
                      ('2b standardization', results_b_std, best_alpha_b_std)]:
    print(f"{label:<22} | {a:>5} | {res[a]['train'][-1]:.4e} | {res[a]['val'][-1]:.4e}")