# -*- coding: utf-8 -*-
"""HW2_Problem_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RsWESjiIsABmNUqQ4zrov7FRpXyyJ1EX
"""

# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from google.colab import drive
# Connect to Google Drive
drive.mount('/content/drive')

# Read the Housing.csv
file_path = '/content/drive/My Drive/Datasets/Housing.csv'
df = pd.DataFrame(pd.read_csv(file_path))

# Map yes/no variables to 1/0 (needed for part b)
binary_vars = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']
df[binary_vars] = df[binary_vars].apply(lambda x: x.map({'yes': 1, 'no': 0}))

print('Number of examples m =', len(df))
df.head()

# Input variables for part a and b
variables_a = ['area', 'bedrooms', 'bathrooms', 'stories', 'parking']
variables_b = ['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'parking', 'prefarea']

# 80/20 split into training and validation set (same split as in Problem 1 and 2)
df_train, df_val = train_test_split(df, train_size=0.8, test_size=0.2, random_state=100)
y_train = df_train['price'].values
y_val = df_val['price'].values
m_train, m_val = len(y_train), len(y_val)
print('Training examples:', m_train, '| Validation examples:', m_val)

# Build data matrices (add X_0 column of ones) with standardization (best scaling from Problem 2)
# The scaler is fitted on the training set only and then applied to the validation set
def build_X(variables):
    scaler = StandardScaler()
    X_tr = scaler.fit_transform(df_train[variables].values.astype(float))
    X_va = scaler.transform(df_val[variables].values.astype(float))
    X_train = np.hstack((np.ones((m_train, 1)), X_tr))
    X_val = np.hstack((np.ones((m_val, 1)), X_va))
    return X_train, X_val

# Cost function (https://github.com/HamedTabkhi/Intro-to-ML/blob/main/IntroCodes/LinearRegression.ipynb)
# used without penalty for the validation set
def compute_cost(X, y, theta):
    """
    Compute cost for linear regression.

    Parameters:
    X : 2D array (m x n), including X_0 column of ones
    y : 1D array of target values. Dimension (m)
    theta : 1D array of fitting parameters. Dimension (n)

    Returns:
    J : Scalar value, the cost
    """
    m = len(y)
    predictions = X.dot(theta)
    errors = np.subtract(predictions, y)
    sqrErrors = np.square(errors)
    J = 1 / (2 * m) * np.sum(sqrErrors)
    return J

# Gradient descent function (https://github.com/HamedTabkhi/Intro-to-ML/blob/main/IntroCodes/LinearRegression.ipynb)
# extended by the validation loss per iteration and the parameter penalty (L2)
# theta_0 (bias) is not penalized, the validation loss stays without penalty
def gradient_descent(X, y, X_val, y_val, theta, alpha, iterations, lambda_):
    m = len(y)
    train_history = np.full(iterations, np.nan)
    val_history = np.full(iterations, np.nan)

    for i in range(iterations):
        with np.errstate(over='ignore', invalid='ignore'):
            predictions = X.dot(theta)
            errors = np.subtract(predictions, y)
            gradient = (1 / m) * X.transpose().dot(errors)
            gradient[1:] += (lambda_ / m) * theta[1:]        # penalty term
            theta = theta - alpha * gradient
            cost = compute_cost(X, y, theta) + (lambda_ / (2 * m)) * np.sum(np.square(theta[1:]))
        if not np.isfinite(cost):
            break
        train_history[i] = cost
        val_history[i] = compute_cost(X_val, y_val, theta)

    return theta, train_history, val_history

# Convergence check
def converged_at(history, delta=1e-6):
    rel_change = np.abs(np.diff(history)) / history[1:]
    idx = np.where(rel_change < delta)[0]
    return int(idx[0]) + 2 if len(idx) > 0 else None

# Training loop over penalty values lambda
# lambda = 0 is the same as Problem 2 (no penalty) and is used for the comparison
def train(variables, alpha, lambdas, iterations):
    X_train, X_val = build_X(variables)
    results = {}

    for lam in lambdas:
        theta0 = np.zeros(X_train.shape[1])
        theta, train_history, val_history = gradient_descent(
            X_train, y_train, X_val, y_val, theta0, alpha, iterations, lam
        )
        results[lam] = {'theta': theta, 'train': train_history, 'val': val_history}

        if np.isnan(train_history[-1]):
            print(f"lambda={lam:<5} | diverged after {np.count_nonzero(~np.isnan(train_history))} iterations")
        else:
            it = converged_at(train_history)
            print(f"lambda={lam:<5} | final train cost={train_history[-1]:.4e} | final val cost={val_history[-1]:.4e} "
                  f"| converged at iteration {it if it else '> ' + str(iterations)}")

    # Best lambda = lowest final validation cost
    best_lambda = min([l for l in lambdas if np.isfinite(results[l]['val'][-1])],
                      key=lambda l: results[l]['val'][-1])
    print('\nBest lambda:', best_lambda)
    for name, t in zip(['theta_0 (bias)'] + variables, results[best_lambda]['theta']):
        print(f"{name:>16s} = {t: .4f}")
    return results, best_lambda

def plot_loss(results, best_lambda, alpha, iterations, title, filename):
    plt.figure(figsize=(10, 6))
    plt.plot(range(1, iterations + 1), results[best_lambda]['train'], label='Training loss (with penalty)')
    plt.plot(range(1, iterations + 1), results[best_lambda]['val'], label='Validation loss')
    plt.xlabel('Iteration')
    plt.ylabel('Cost J(theta)')
    plt.yscale('log')
    plt.title(f'{title} (alpha={alpha}, lambda={best_lambda})')
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig(filename, dpi=110)
    plt.show()

# Training settings (best learning rate and scaling from Problem 2)
iterations = 2000
alpha = 0.1
lambdas = [0, 10, 50, 100]

# Training for a)
print('--- a) Standardization + parameter penalty ---')
results_a, best_lambda_a = train(variables_a, alpha, lambdas, iterations)

# Plotting for a)
plot_loss(results_a, best_lambda_a, alpha, iterations, 'Problem 3a: Training and Validation Loss', 'problem_3a_loss.png')

# Training for b)
print('\n--- b) Standardization + parameter penalty ---')
results_b, best_lambda_b = train(variables_b, alpha, lambdas, iterations)

# Plotting for b)
plot_loss(results_b, best_lambda_b, alpha, iterations, 'Problem 3b: Training and Validation Loss', 'problem_3b_loss.png')

# Comparison Problem 2 (lambda = 0) vs. Problem 3 (with penalty)
print(f"\n{'Model':<6} | {'lambda':>6} | {'train cost':>11} | {'val cost':>11}")
for label, res in [('3a', results_a), ('3b', results_b)]:
    for lam in lambdas:
        print(f"{label:<6} | {lam:>6} | {res[lam]['train'][-1]:.4e} | {res[lam]['val'][-1]:.4e}")